version: "3"
services:
#######
# Business 1
#######
  bpa1:
    image: ghcr.io/hyperledger-labs/business-partner-agent:local
    build:
      context: ../../..
      dockerfile: Dockerfile
    depends_on:
      - bpa-agent1
    environment:
      JAVA_OPTS: >
        -Dbpa.acapy.url=http://bpa-agent1:${ACAPY1_ADMIN_PORT}
        -Dbpa.acapy.apiKey=${ACAPY_ADMIN_URL_API_KEY}
        -Dmicronaut.security.enabled=${BPA_SECURITY_ENABLED}
        -Dmicronaut.server.port=${BPA1_PORT}
        -Dmicronaut.environments=dev
        -Dmicronaut.config.files=${BPA_CONFIG_FILES}
        -Dbpa.pg.url=jdbc:postgresql://${POSTGRESQL1_HOST}/${POSTGRESQL_USER}
        -Dbpa.pg.username=${POSTGRESQL_USER}
        -Dbpa.pg.password=${POSTGRESQL_PASSWORD}
        -Dbpa.host=${BPA_HOST}:${BPA1_PORT}
        -Dbpa.scheme=${BPA_SCHEME}
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${BPA1_DEBUG_PORT}
      BPA_WEB_MODE: ${BPA_WEB_MODE}
      BPA_LEDGER_BROWSER: ${BPA_LEDGER_BROWSER}
      BPA_BOOTSTRAP_UN: ${BPA_BOOTSTRAP_UN}
      BPA_BOOTSTRAP_PW: ${BPA_BOOTSTRAP_PW}
      ACAPY_ENDPOINT: ${ACAPY1_ENDPOINT}
      AGENT_NAME: ${AGENT1_NAME}
      BPA_IMPRINT_URL: ${BPA_IMPRINT_URL}
      BPA_PRIVACY_POLICY_URL: ${BPA_PRIVACY_POLICY_URL}
      BPA_CREDDEF_REVOCATION_REGISTRY_SIZE: ${BPA_CREDDEF_REVOCATION_REGISTRY_SIZE}
      NODE_ENV: development
    ports:
      - ${BPA1_PORT}:${BPA1_PORT}
      - ${BPA1_DEBUG_PORT}:${BPA1_DEBUG_PORT}
    restart: always
    extra_hosts:
     - host.docker.internal:host-gateway
  bpa-agent1:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.3
    ports:
      - ${ACAPY1_ADMIN_PORT}:${ACAPY1_ADMIN_PORT}
      - ${ACAPY1_HTTP_PORT}:${ACAPY1_HTTP_PORT}
    depends_on:
      - bpa-wallet-db1
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 1;
        aca-py start \
        --auto-provision
        --arg-file acapy-static-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY1_HTTP_PORT} \
        --webhook-url http://bpa1:${BPA1_PORT}/log \
        --genesis-url '${ACAPY_GENESIS_URL}' \
        --endpoint ${ACAPY1_ENDPOINT} \
        --wallet-name '${ACAPY_WALLET_DATABASE}' \
        --wallet-key '${ACAPY_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${ACAPY_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL1_HOST}:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_USER}\",\"admin_password\":\"${POSTGRESQL_PASSWORD}\"}' \
        --seed '${ACAPY_SEED1}' \
        --admin '0.0.0.0' ${ACAPY1_ADMIN_PORT} \
        --label '${AGENT1_NAME}' \
        ${ACAPY_ADMIN_CONFIG} \
        ${ACAPY_READ_ONLY_MODE} \
        ${ACAPY_TAILS_BASE_URL} \
        ${ACAPY_TAILS_UPLOAD_URL} \
        "
      ]
    volumes:
      - "./acapy-static-args.yml:/home/indy/acapy-static-args.yml"
    extra_hosts:
     - host.docker.internal:host-gateway
  bpa-wallet-db1:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL1_PORT}:5432
    volumes:
      - bpa-wallet-db1:/var/lib/postgresql/data

#######
# Business 2
#######
  bpa2:
    build:
      context: ../../..
      dockerfile: Dockerfile
    depends_on:
      -  bpa-agent2
    environment:
      JAVA_OPTS: >
        -Dbpa.acapy.url=http://bpa-agent2:${ACAPY2_ADMIN_PORT}
        -Dbpa.acapy.apiKey=${ACAPY_ADMIN_URL_API_KEY}
        -Dmicronaut.security.enabled=${BPA_SECURITY_ENABLED}
        -Dmicronaut.server.port=${BPA2_PORT}
        -Dmicronaut.environments=dev
        -Dmicronaut.config.files=${BPA_CONFIG_FILES}
        -Dbpa.pg.url=jdbc:postgresql://${POSTGRESQL2_HOST}/${POSTGRESQL_USER}
        -Dbpa.pg.username=${POSTGRESQL_USER}
        -Dbpa.pg.password=${POSTGRESQL_PASSWORD}
        -Dbpa.host=${BPA_HOST}:${BPA2_PORT}
        -Dbpa.scheme=${BPA_SCHEME}
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${BPA2_DEBUG_PORT}
      BPA_WEB_MODE: ${BPA_WEB_MODE}
      BPA_LEDGER_BROWSER: ${BPA_LEDGER_BROWSER}
      BPA_BOOTSTRAP_UN: ${BPA_BOOTSTRAP_UN}
      BPA_BOOTSTRAP_PW: ${BPA_BOOTSTRAP_PW}
      ACAPY_ENDPOINT: ${ACAPY2_ENDPOINT}
      AGENT_NAME: ${AGENT2_NAME}
      BPA_IMPRINT_URL: ${BPA_IMPRINT_URL}
      BPA_PRIVACY_POLICY_URL: ${BPA_PRIVACY_POLICY_URL}
      BPA_CREDDEF_REVOCATION_REGISTRY_SIZE: ${BPA_CREDDEF_REVOCATION_REGISTRY_SIZE}
      NODE_ENV: development
    ports:
      - ${BPA2_PORT}:${BPA2_PORT}
      - ${BPA2_DEBUG_PORT}:${BPA2_DEBUG_PORT}
    restart: always
    extra_hosts:
     - host.docker.internal:host-gateway
  bpa-agent2:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.3
    ports:
      - ${ACAPY2_ADMIN_PORT}:${ACAPY2_ADMIN_PORT}
      - ${ACAPY2_HTTP_PORT}:${ACAPY2_HTTP_PORT}
    depends_on:
      - bpa-wallet-db2
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 1;
        aca-py start \
        --auto-provision
        --arg-file acapy-static-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY2_HTTP_PORT} \
        --webhook-url http://bpa2:${BPA2_PORT}/log \
        --genesis-url '${ACAPY_GENESIS_URL}' \
        --endpoint ${ACAPY2_ENDPOINT} \
        --wallet-name '${ACAPY_WALLET_DATABASE}' \
        --wallet-key '${ACAPY_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${ACAPY_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL2_HOST}:5432\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_USER}\",\"admin_password\":\"${POSTGRESQL_PASSWORD}\"}' \
        --seed '${ACAPY_SEED2}' \
        --admin '0.0.0.0' ${ACAPY2_ADMIN_PORT} \
        --label '${AGENT2_NAME}' \
        ${ACAPY_ADMIN_CONFIG} \
        ${ACAPY_READ_ONLY_MODE} \
        ${ACAPY_TAILS_BASE_URL} \
        ${ACAPY_TAILS_UPLOAD_URL} \
        "
      ]
    volumes:
      - "./acapy-static-args.yml:/home/indy/acapy-static-args.yml"
    extra_hosts:
     - host.docker.internal:host-gateway
  bpa-wallet-db2:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - ${POSTGRESQL2_PORT}:5432
    volumes:
      - bpa-wallet-db2:/var/lib/postgresql/data

  #######
  # Tails Server for Revocation support
  #######
  tails-server:
    build:
      context: https://github.com/bcgov/indy-tails-server.git#main
      dockerfile: docker/Dockerfile.tails-server
    ports:
      - "6543:6543"
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /home/indy/tails-server-files
        --log-level DEBUG
    # container runs as user indy, but mount belongs to root
    # needs change in Dockerfile to fix the permissions
    user: root
    volumes:
      - tails-data:/home/indy/tails-server-files



volumes:
  bpa-wallet-db1:
  bpa-wallet-db2:
  tails-data:
