apiVersion: v2
name: bpa
description: The Business Partner Agent allows to manage and exchange master data between organizations.
type: application

version: 0.2.0-alpha03
appVersion: 0.1.0-alpha10

home: "https://github.com/hyperledger-labs/business-partner-agent/tree/master/charts/bpa"
sources: ["https://github.com/hyperledger-labs/business-partner-agent/tree/master/charts/bpa"]
engine: gotpl
maintainers:
  - email: Frank.Bernhardt@bosch.com
    name: Frank Bernhardt
  - email: jason.syrotuck@nttdata.com
    name: Jason Syrotuck
dependencies:
  - name: postgresql
    version: 10.3.13
    repository: https://charts.bitnami.com/bitnami/
    condition: persistence.deployPostgres
