apiVersion: v2
name: bpa
description: The Business Partner Agent allows to manage and exchange master data between organizations.
type: application
version: 0.1.0-alpha2.3

appVersion: latest

home: "https://github.com/hyperledger-labs/business-partner-agent/tree/master/charts/bpa"
sources: ["https://github.com/hyperledger-labs/business-partner-agent/tree/master/charts/bpa"]
engine: gotpl
maintainers:
  - email: Frank.Bernhardt@bosch.com
    name: Frank Bernhardt

dependencies:
  - name: postgresql
    version: 10.1.3
    repository: https://charts.bitnami.com/bitnami/
    condition: persistence.deployPostgres
