# Compose file for frontent developers or for everyone else that needs the full stack up and running

version: '3'

services:
  aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.15-0_0.5.6
    ports:
      - ${ACAPY_ADMIN_PORT}:${ACAPY_ADMIN_PORT}
      - ${ACAPY_HTTP_PORT}:${ACAPY_HTTP_PORT}
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 1;
        aca-py start \
        --arg-file acapy-static-args.yml \
        --inbound-transport http '0.0.0.0' ${ACAPY_HTTP_PORT} \
        --endpoint ${ACAPY_ENDPOINT} \
        --profile-endpoint https://${BPA_HOST}/profile.jsonld \
        --webhook-url http://localhost:${BPA_PORT}/log \
        --genesis-url '${ACAPY_GENESIS_URL}' \
        --seed '${ACAPY_SEED}' \
        --admin '0.0.0.0' ${ACAPY_ADMIN_PORT} \
        --admin-insecure-mode \
        --label ${AGENT_NAME} \
        "
      ]