version: "3.9"
services:
  bpa-agent1:
    build:
      context: ${ACAPY_BUILD_CONTEXT}
      dockerfile: ${ACAPY_BUILD_DOCKERFILE_PATH}
  bpa-agent2:
    build:
      context: ${ACAPY_BUILD_CONTEXT}
      dockerfile: ${ACAPY_BUILD_DOCKERFILE_PATH}      