apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bpa.fullname" . }}
  labels:
    {{- include "bpa.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bpa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.bpa.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "bpa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.bpa.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bpa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.bpa.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.bpa.name }}
          securityContext:
            {{- toYaml .Values.bpa.securityContext | nindent 12 }}
          image: "{{ .Values.bpa.image.repository }}:{{ .Values.bpa.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bpa.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "global.postgresql.fullname" . }}
                  key: postgresql-password
            {{- include "bpa.keycloak.secret.env.vars" . | nindent 12}}
            - name: JAVA_OPTS
              value: |
                -Dbpa.pg.password=$(POSTGRES_PASSWORD)
                -Dmicronaut.config.files={{ include "bpa.config.files" . }}
            {{- include "bpa.application.configmap.env.vars" . | nindent 10}}
            {{- include "bpa.keycloak.configmap.env.vars" . | nindent 10}}
          {{- include "bpa.schemas.volume.mount" . | nindent 10}}
          resources:
            {{- toYaml .Values.bpa.resources | nindent 12 }}
          {{- include "bpa.schemas.volume" . | nindent 6}}
      {{- with .Values.bpa.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bpa.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bpa.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
